"""Usage: python3 ci/icon/gen.py app/src/main/res <preview dir>

Generate the Isaialai launcher icon (original 'vibing listener' character) as Android
vector drawables, plus an SVG preview built from the same shapes."""
import math, os, sys

OUT_RES = sys.argv[1]          # app/src/main/res
OUT_PREVIEW = sys.argv[2]      # preview dir

def circle(cx, cy, r): return f"M{cx-r},{cy} a{r},{r} 0 1,0 {2*r},0 a{r},{r} 0 1,0 {-2*r},0 z"
def ellipse(cx, cy, rx, ry): return f"M{cx-rx},{cy} a{rx},{ry} 0 1,0 {2*rx},0 a{rx},{ry} 0 1,0 {-2*rx},0 z"
def rrect(x, y, w, h, r):
    return (f"M{x+r},{y} h{w-2*r} a{r},{r} 0 0 1 {r},{r} v{h-2*r} a{r},{r} 0 0 1 {-r},{r} "
            f"h{-(w-2*r)} a{r},{r} 0 0 1 {-r},{-r} v{-(h-2*r)} a{r},{r} 0 0 1 {r},{-r} z")
def star(x, y, r): return f"M{x},{y-r} Q{x},{y} {x+r},{y} Q{x},{y} {x},{y+r} Q{x},{y} {x-r},{y} Q{x},{y} {x},{y-r} z"
def note(x, y, s):
    # note head (tilted ellipse approximated by rotating points), stem, flag
    pts = []
    for i in range(0, 361, 30):
        t = math.radians(i); a = math.radians(-20)
        px, py = 6 * math.cos(t), 4.6 * math.sin(t)
        pts.append((x + s * (px * math.cos(a) - py * math.sin(a)), y + s * (px * math.sin(a) + py * math.cos(a))))
    head = "M" + " L".join(f"{px:.2f},{py:.2f}" for px, py in pts) + " z"
    stem = rrect(x + s * 4.2, y - s * 22, s * 3, s * 22, s * 1.5)
    flag = f"M{x + s*7},{y - s*22} q{s*10},{s*3} {s*10},{s*13}"
    return head + " " + stem, flag

SKIN, HAIR, INK, HOODIE = "#B97A55", "#17101F", "#2A1A14", "#1B1430"

# Shapes: (kind, path, attrs). kind = fill | stroke
shapes = []
def fill(d, color, alpha=1.0): shapes.append(("fill", d, color, alpha, 0))
def stroke(d, color, width, alpha=1.0): shapes.append(("stroke", d, color, alpha, width))

fill("M28,192 C32,152 60,136 96,136 C132,136 160,152 164,192 Z", HOODIE)
stroke("M74,138 C80,158 112,158 118,138", "#000000", 6, 0.25)
stroke("M86,150 L84,172 M106,150 L108,172", "#FFFFFF", 3, 0.85)
fill(rrect(85, 120, 22, 20, 8), "#9C6544")
fill(ellipse(96, 94, 32, 36), SKIN)
stroke("M78,92 Q84,98 90,92", INK, 3.6)
stroke("M102,92 Q108,98 114,92", INK, 3.6)
stroke("M87,109 Q96,118 105,109", INK, 3.6)
fill(ellipse(76, 104, 6, 3.4), "#E9806E", 0.5)
fill(ellipse(116, 104, 6, 3.4), "#E9806E", 0.5)
fill("M63,88 C60,66 72,54 96,52 C120,54 132,66 129,88 C122,74 110,70 96,70 C82,70 70,74 63,88 Z", HAIR)
for cx, cy, r in [(70,66,12),(82,55,13),(97,51,14),(112,55,13),(124,66,11),(88,68,9),(106,68,9)]:
    fill(circle(cx, cy, r), HAIR)
stroke("M55,98 C50,40 142,40 137,98", "#FFFFFF", 9)
fill(rrect(43, 80, 24, 38, 12), "#FFFFFF"); fill(rrect(47.5, 85, 15, 28, 7.5), "#FF7A59")
fill(rrect(125, 80, 24, 38, 12), "#FFFFFF"); fill(rrect(129.5, 85, 15, 28, 7.5), "#FF7A59")
fill(rrect(50, 88, 3, 10, 1.5), "#FFFFFF", 0.6)
h, f = note(152, 58, 1.0); fill(h, "#FFFFFF", 0.9); stroke(f, "#FFFFFF", 3, 0.9)
h, f = note(36, 50, 0.7); fill(h, "#FFFFFF", 0.7); stroke(f, "#FFFFFF", 2.1, 0.7)
fill(star(160, 104, 7), "#FFFFFF", 0.9); fill(star(30, 92, 5), "#FFFFFF", 0.7); fill(star(140, 24, 4), "#FFFFFF", 0.6)

# Pull the art in a little so the face and headphones sit inside every launcher mask.
SCALE = 0.74
PIVOT = 96

def vd_path(kind, d, color, alpha, width):
    a = f'android:fillAlpha="{alpha}"' if kind == "fill" else f'android:strokeAlpha="{alpha}"'
    if kind == "fill":
        return f'        <path android:fillColor="{color}" {a} android:pathData="{d}" />'
    return (f'        <path android:strokeColor="{color}" {a} android:strokeWidth="{width}" '
            f'android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{d}" />')

fg = ['<?xml version="1.0" encoding="utf-8"?>',
      '<!-- Isaialai launcher art: an original young listener vibing to music. Generated by ci/icon/gen.py. -->',
      '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
      '    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">',
      f'    <group android:pivotX="{PIVOT}" android:pivotY="{PIVOT}" android:scaleX="{SCALE}" android:scaleY="{SCALE}">']
fg += [vd_path(*s) for s in shapes]
fg += ['    </group>', '</vector>']

bg = '''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">
    <path android:pathData="M0,0h192v192h-192z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="192" android:endY="192"
                android:startColor="#8E6BFF" android:endColor="#FF7A59" />
        </aapt:attr>
    </path>
    <path android:pathData="''' + circle(96, 88, 84) + '''">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="96" android:centerY="88" android:gradientRadius="84"
                android:startColor="#47FFFFFF" android:endColor="#00FFFFFF" />
        </aapt:attr>
    </path>
</vector>
'''

# Themed (monochrome) icon: just the headphones, face outline and the happy closed eyes.
mono_parts = [
    ("stroke", "M55,98 C50,40 142,40 137,98", 10),
    ("fill", rrect(43, 80, 24, 38, 12), 0), ("fill", rrect(125, 80, 24, 38, 12), 0),
    ("stroke", ellipse(96, 98, 30, 34), 6),
    ("stroke", "M80,96 Q86,102 92,96", 5), ("stroke", "M100,96 Q106,102 112,96", 5),
    ("stroke", "M87,112 Q96,121 105,112", 5),
]
mono = ['<?xml version="1.0" encoding="utf-8"?>',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp" android:height="108dp" android:viewportWidth="192" android:viewportHeight="192">',
        f'    <group android:pivotX="{PIVOT}" android:pivotY="{PIVOT}" android:scaleX="0.8" android:scaleY="0.8">']
for kind, d, w in mono_parts:
    if kind == "fill": mono.append(f'        <path android:fillColor="#FFFFFF" android:pathData="{d}" />')
    else: mono.append(f'        <path android:strokeColor="#FFFFFF" android:strokeWidth="{w}" android:strokeLineCap="round" android:pathData="{d}" />')
mono += ['    </group>', '</vector>']

os.makedirs(f"{OUT_RES}/drawable", exist_ok=True)
open(f"{OUT_RES}/drawable/ic_launcher_foreground.xml", "w").write("\n".join(fg) + "\n")
open(f"{OUT_RES}/drawable/ic_launcher_background.xml", "w").write(bg)
open(f"{OUT_RES}/drawable/ic_launcher_monochrome.xml", "w").write("\n".join(mono) + "\n")

# SVG preview from the same shapes, shown in the masks launchers use.
def svg_shapes(scale=SCALE):
    out = [f'<g transform="translate({PIVOT} {PIVOT}) scale({scale}) translate({-PIVOT} {-PIVOT})">']
    for kind, d, color, alpha, width in shapes:
        if kind == "fill": out.append(f'<path d="{d}" fill="{color}" fill-opacity="{alpha}"/>')
        else: out.append(f'<path d="{d}" fill="none" stroke="{color}" stroke-opacity="{alpha}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"/>')
    return "\n".join(out) + "</g>"
bg_svg = f'''<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#8E6BFF"/><stop offset="1" stop-color="#FF7A59"/></linearGradient>
<radialGradient id="r" cx="96" cy="88" r="84" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fff" stop-opacity=".28"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs>
<rect width="192" height="192" fill="url(#g)"/><path d="{circle(96,88,84)}" fill="url(#r)"/>'''
mono_svg = "".join((f'<path d="{d}" fill="#3B2F5E"/>' if k == "fill" else f'<path d="{d}" fill="none" stroke="#3B2F5E" stroke-width="{w}" stroke-linecap="round"/>') for k, d, w in mono_parts)
# Adaptive icon: 108dp canvas, launcher shows the middle 72dp (scale 1.5), cropped by a mask.
def masked(clip):
    return (f'<svg viewBox="0 0 192 192" width="180" height="180"><defs><clipPath id="c{abs(hash(clip))}">{clip}</clipPath></defs>'
            f'<g clip-path="url(#c{abs(hash(clip))})"><g transform="translate(96 96) scale(1.5) translate(-96 -96)">{bg_svg}{svg_shapes()}</g></g></svg>')
html = f'''<!doctype html><html><body style="margin:0;background:#101015;color:#ddd;font-family:Arial">
<div style="display:flex;gap:28px;padding:30px;align-items:flex-end">
<div style="text-align:center">{masked('<circle cx="96" cy="96" r="96"/>')}<div>Circle</div></div>
<div style="text-align:center">{masked('<rect width="192" height="192" rx="44"/>')}<div>Rounded square</div></div>
<div style="text-align:center">{masked('<path d="M96 0 C170 0 192 22 192 96 S170 192 96 192 0 170 0 96 22 0 96 0Z"/>')}<div>Squircle</div></div>
<div style="text-align:center"><svg viewBox="0 0 192 192" width="180" height="180"><circle cx="96" cy="96" r="96" fill="#E8E0FF"/><g transform="translate(96 96) scale(1.2) translate(-96 -96)">{mono_svg}</g></svg><div>Themed (Android 13+)</div></div>
<div style="text-align:center"><div style="width:56px;height:56px;border-radius:50%;overflow:hidden;margin:0 auto">{masked('<circle cx="96" cy="96" r="96"/>').replace('width="180" height="180"','width="56" height="56"')}</div><div style="font-size:13px;margin-top:6px">Isaialai</div></div>
</div></body></html>'''
os.makedirs(OUT_PREVIEW, exist_ok=True)
open(f"{OUT_PREVIEW}/preview.html", "w").write(html)
print("ok")
